version: '3.8'

services:
  redis:
    image: redis
    command: ["redis-server", "--bind", "0.0.0.0"]
    ports:
      - "6379:6379"
    networks:
      - backend_network

  mongo:
    image: mongo
    container_name: mongo
    command: ["mongod", "--bind_ip", "0.0.0.0"]  # Lắng nghe trên tất cả các IP
    ports:
      - "27017:27017"  # Mở cổng MongoDB
    networks:
      - backend_network
    # Loại bỏ environment với tài khoản mật khẩu
    environment: []

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - IOREDIS_IS_ENABLE=true
      - IOREDIS_HOST=redis
      - IOREDIS_PORT=6379
      # Cập nhật URI MongoDB để không có tài khoản mật khẩu
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - redis
      - mongo
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
